services:
  - type: web
    name: certchain-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: RPC_URL
        sync: false        # set manually in Render dashboard
      - key: DEPLOYER_PRIVATE_KEY
        sync: false        # set manually in Render dashboard
      - key: FRONTEND_URL
        sync: false        # set to your Vercel URL after deploying frontend
